# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  # adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000
  adapter: mysql2
  encoding: utf8
  username: b669f0f0843ada
  password: 17ce4030
  host: mysql://b669f0f0843ada:17ce4030@us-cdbr-east-06.cleardb.net/heroku_482c557b814620c?reconnect=true
  database: heroku_482c557b814620c

development:
  <<: *default
  database: heroku_482c557b814620c

production:
  <<: *default
  database: heroku_482c557b814620c
  username: b669f0f0843ada
  password: 17ce4030
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>